name: GitHubViewer
options:
  bundleIdPrefix: jp.blk
  deploymentTarget:
    iOS: 15.0
  tabWidth: 2
  indentWidth: 2
  xcodeVersion: 14.3.1

settings:
  base:
    MARKETING_VERSION: 1.0.0

targets:
  GitHubViewer:
    type: application
    platform: iOS
    sources: 
      - GitHubViewer
    info:
      path: GitHubViewer/info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""

