name: GitHubViewer
options:
  bundleIdPrefix: jp.blk
  deploymentTarget:
    iOS: 15.0
  tabWidth: 2
  indentWidth: 2
  xcodeVersion: 14.3.1

settings:
  base:
    MARKETING_VERSION: 1.0.0

targets:
  GitHubViewer:
    type: application
    platform: iOS
    sources: 
      - GitHubViewer
    info:
      path: GitHubViewer/info.plist
      properties:
        CFBundleAllowMixedLocalizations: YES
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""
    dependencies:
      - package: Common
        product: SharedResource
      - package: Network
        product: API

packages:
  # Local packages
  Common:
    path: ./Modules/Common
  Network:
    path: ./Modules/Network