import API
import Dependencies
import Foundation
import XCTest
@testable import RepoRepository

final class RepoRepositoryTests: XCTestCase {
  func testRepositories() async throws {
    let repoRepository: RepoRepository = withDependencies({
      $0.apiClient.request = { _ -> (Data, URLResponse) in
        return mockResponse(value: .gitHubUserReposSuccessJSON, statusCode: 200)
      }
    }, operation: {
      RepoRepository.liveValue
    })
    let repositories = try await repoRepository.repositories("beryu", 1)
    XCTAssertEqual(repositories.count, 2)
    XCTAssertEqual(repositories.first!.name, "APIKit")
    XCTAssertEqual(repositories.first!.fullName, "beryu/APIKit")
    XCTAssertEqual(repositories.first!.description, "Type-safe networking abstraction layer that associates request type with response type.")
  }
}

extension String {
  static fileprivate var gitHubUserReposSuccessJSON: String =
    """
[
    {
        "id": 176659883,
        "node_id": "MDEwOlJlcG9zaXRvcnkxNzY2NTk4ODM=",
        "name": "APIKit",
        "full_name": "beryu/APIKit",
        "private": false,
        "owner": {
            "login": "beryu",
            "id": 202968,
            "node_id": "MDQ6VXNlcjIwMjk2OA==",
            "avatar_url": "https://avatars.githubusercontent.com/u/202968?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/beryu",
            "html_url": "https://github.com/beryu",
            "followers_url": "https://api.github.com/users/beryu/followers",
            "following_url": "https://api.github.com/users/beryu/following{/other_user}",
            "gists_url": "https://api.github.com/users/beryu/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/beryu/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/beryu/subscriptions",
            "organizations_url": "https://api.github.com/users/beryu/orgs",
            "repos_url": "https://api.github.com/users/beryu/repos",
            "events_url": "https://api.github.com/users/beryu/events{/privacy}",
            "received_events_url": "https://api.github.com/users/beryu/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/beryu/APIKit",
        "description": "Type-safe networking abstraction layer that associates request type with response type.",
        "fork": true,
        "url": "https://api.github.com/repos/beryu/APIKit",
        "forks_url": "https://api.github.com/repos/beryu/APIKit/forks",
        "keys_url": "https://api.github.com/repos/beryu/APIKit/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/beryu/APIKit/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/beryu/APIKit/teams",
        "hooks_url": "https://api.github.com/repos/beryu/APIKit/hooks",
        "issue_events_url": "https://api.github.com/repos/beryu/APIKit/issues/events{/number}",
        "events_url": "https://api.github.com/repos/beryu/APIKit/events",
        "assignees_url": "https://api.github.com/repos/beryu/APIKit/assignees{/user}",
        "branches_url": "https://api.github.com/repos/beryu/APIKit/branches{/branch}",
        "tags_url": "https://api.github.com/repos/beryu/APIKit/tags",
        "blobs_url": "https://api.github.com/repos/beryu/APIKit/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/beryu/APIKit/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/beryu/APIKit/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/beryu/APIKit/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/beryu/APIKit/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/beryu/APIKit/languages",
        "stargazers_url": "https://api.github.com/repos/beryu/APIKit/stargazers",
        "contributors_url": "https://api.github.com/repos/beryu/APIKit/contributors",
        "subscribers_url": "https://api.github.com/repos/beryu/APIKit/subscribers",
        "subscription_url": "https://api.github.com/repos/beryu/APIKit/subscription",
        "commits_url": "https://api.github.com/repos/beryu/APIKit/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/beryu/APIKit/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/beryu/APIKit/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/beryu/APIKit/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/beryu/APIKit/contents/{+path}",
        "compare_url": "https://api.github.com/repos/beryu/APIKit/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/beryu/APIKit/merges",
        "archive_url": "https://api.github.com/repos/beryu/APIKit/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/beryu/APIKit/downloads",
        "issues_url": "https://api.github.com/repos/beryu/APIKit/issues{/number}",
        "pulls_url": "https://api.github.com/repos/beryu/APIKit/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/beryu/APIKit/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/beryu/APIKit/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/beryu/APIKit/labels{/name}",
        "releases_url": "https://api.github.com/repos/beryu/APIKit/releases{/id}",
        "deployments_url": "https://api.github.com/repos/beryu/APIKit/deployments",
        "created_at": "2019-03-20T05:22:04Z",
        "updated_at": "2019-03-20T05:22:07Z",
        "pushed_at": "2018-10-29T14:21:44Z",
        "git_url": "git://github.com/beryu/APIKit.git",
        "ssh_url": "git@github.com:beryu/APIKit.git",
        "clone_url": "https://github.com/beryu/APIKit.git",
        "svn_url": "https://github.com/beryu/APIKit",
        "homepage": "",
        "size": 1355,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Swift",
        "has_issues": false,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
            "key": "mit",
            "name": "MIT License",
            "spdx_id": "MIT",
            "url": "https://api.github.com/licenses/mit",
            "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master",
        "permissions": {
            "admin": true,
            "maintain": true,
            "push": true,
            "triage": true,
            "pull": true
        }
    },
    {
        "id": 105371809,
        "node_id": "MDEwOlJlcG9zaXRvcnkxMDUzNzE4MDk=",
        "name": "ARKit-Sampler",
        "full_name": "beryu/ARKit-Sampler",
        "private": false,
        "owner": {
            "login": "beryu",
            "id": 202968,
            "node_id": "MDQ6VXNlcjIwMjk2OA==",
            "avatar_url": "https://avatars.githubusercontent.com/u/202968?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/beryu",
            "html_url": "https://github.com/beryu",
            "followers_url": "https://api.github.com/users/beryu/followers",
            "following_url": "https://api.github.com/users/beryu/following{/other_user}",
            "gists_url": "https://api.github.com/users/beryu/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/beryu/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/beryu/subscriptions",
            "organizations_url": "https://api.github.com/users/beryu/orgs",
            "repos_url": "https://api.github.com/users/beryu/repos",
            "events_url": "https://api.github.com/users/beryu/events{/privacy}",
            "received_events_url": "https://api.github.com/users/beryu/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/beryu/ARKit-Sampler",
        "description": "Code examples for ARKit.",
        "fork": true,
        "url": "https://api.github.com/repos/beryu/ARKit-Sampler",
        "forks_url": "https://api.github.com/repos/beryu/ARKit-Sampler/forks",
        "keys_url": "https://api.github.com/repos/beryu/ARKit-Sampler/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/beryu/ARKit-Sampler/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/beryu/ARKit-Sampler/teams",
        "hooks_url": "https://api.github.com/repos/beryu/ARKit-Sampler/hooks",
        "issue_events_url": "https://api.github.com/repos/beryu/ARKit-Sampler/issues/events{/number}",
        "events_url": "https://api.github.com/repos/beryu/ARKit-Sampler/events",
        "assignees_url": "https://api.github.com/repos/beryu/ARKit-Sampler/assignees{/user}",
        "branches_url": "https://api.github.com/repos/beryu/ARKit-Sampler/branches{/branch}",
        "tags_url": "https://api.github.com/repos/beryu/ARKit-Sampler/tags",
        "blobs_url": "https://api.github.com/repos/beryu/ARKit-Sampler/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/beryu/ARKit-Sampler/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/beryu/ARKit-Sampler/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/beryu/ARKit-Sampler/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/beryu/ARKit-Sampler/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/beryu/ARKit-Sampler/languages",
        "stargazers_url": "https://api.github.com/repos/beryu/ARKit-Sampler/stargazers",
        "contributors_url": "https://api.github.com/repos/beryu/ARKit-Sampler/contributors",
        "subscribers_url": "https://api.github.com/repos/beryu/ARKit-Sampler/subscribers",
        "subscription_url": "https://api.github.com/repos/beryu/ARKit-Sampler/subscription",
        "commits_url": "https://api.github.com/repos/beryu/ARKit-Sampler/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/beryu/ARKit-Sampler/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/beryu/ARKit-Sampler/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/beryu/ARKit-Sampler/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/beryu/ARKit-Sampler/contents/{+path}",
        "compare_url": "https://api.github.com/repos/beryu/ARKit-Sampler/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/beryu/ARKit-Sampler/merges",
        "archive_url": "https://api.github.com/repos/beryu/ARKit-Sampler/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/beryu/ARKit-Sampler/downloads",
        "issues_url": "https://api.github.com/repos/beryu/ARKit-Sampler/issues{/number}",
        "pulls_url": "https://api.github.com/repos/beryu/ARKit-Sampler/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/beryu/ARKit-Sampler/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/beryu/ARKit-Sampler/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/beryu/ARKit-Sampler/labels{/name}",
        "releases_url": "https://api.github.com/repos/beryu/ARKit-Sampler/releases{/id}",
        "deployments_url": "https://api.github.com/repos/beryu/ARKit-Sampler/deployments",
        "created_at": "2017-09-30T13:29:58Z",
        "updated_at": "2017-09-30T13:30:00Z",
        "pushed_at": "2017-09-24T21:53:39Z",
        "git_url": "git://github.com/beryu/ARKit-Sampler.git",
        "ssh_url": "git@github.com:beryu/ARKit-Sampler.git",
        "clone_url": "https://github.com/beryu/ARKit-Sampler.git",
        "svn_url": "https://github.com/beryu/ARKit-Sampler",
        "homepage": "",
        "size": 25165,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Swift",
        "has_issues": false,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
            "key": "mit",
            "name": "MIT License",
            "spdx_id": "MIT",
            "url": "https://api.github.com/licenses/mit",
            "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master",
        "permissions": {
            "admin": true,
            "maintain": true,
            "push": true,
            "triage": true,
            "pull": true
        }
    }
]
"""
}
